// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flow/entities/account.proto

package org.onflow.protobuf.entities;

public final class AccountOuterClass {
  private AccountOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:flow.entities.Account)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes address = 1;</code>
     * @return The address.
     */
    com.google.protobuf.ByteString getAddress();

    /**
     * <code>uint64 balance = 2;</code>
     * @return The balance.
     */
    long getBalance();

    /**
     * <code>bytes code = 3;</code>
     * @return The code.
     */
    com.google.protobuf.ByteString getCode();

    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    java.util.List<org.onflow.protobuf.entities.AccountOuterClass.AccountKey> 
        getKeysList();
    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    org.onflow.protobuf.entities.AccountOuterClass.AccountKey getKeys(int index);
    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    int getKeysCount();
    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    java.util.List<? extends org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder> 
        getKeysOrBuilderList();
    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder getKeysOrBuilder(
        int index);

    /**
     * <code>map&lt;string, bytes&gt; contracts = 5;</code>
     */
    int getContractsCount();
    /**
     * <code>map&lt;string, bytes&gt; contracts = 5;</code>
     */
    boolean containsContracts(
        java.lang.String key);
    /**
     * Use {@link #getContractsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getContracts();
    /**
     * <code>map&lt;string, bytes&gt; contracts = 5;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getContractsMap();
    /**
     * <code>map&lt;string, bytes&gt; contracts = 5;</code>
     */

    com.google.protobuf.ByteString getContractsOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue);
    /**
     * <code>map&lt;string, bytes&gt; contracts = 5;</code>
     */

    com.google.protobuf.ByteString getContractsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code flow.entities.Account}
   */
  public static final class Account extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:flow.entities.Account)
      AccountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Account() {
      address_ = com.google.protobuf.ByteString.EMPTY;
      code_ = com.google.protobuf.ByteString.EMPTY;
      keys_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Account();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Account(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              address_ = input.readBytes();
              break;
            }
            case 16: {

              balance_ = input.readUInt64();
              break;
            }
            case 26: {

              code_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                keys_ = new java.util.ArrayList<org.onflow.protobuf.entities.AccountOuterClass.AccountKey>();
                mutable_bitField0_ |= 0x00000001;
              }
              keys_.add(
                  input.readMessage(org.onflow.protobuf.entities.AccountOuterClass.AccountKey.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                contracts_ = com.google.protobuf.MapField.newMapField(
                    ContractsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
              contracts__ = input.readMessage(
                  ContractsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              contracts_.getMutableMap().put(
                  contracts__.getKey(), contracts__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          keys_ = java.util.Collections.unmodifiableList(keys_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_Account_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetContracts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onflow.protobuf.entities.AccountOuterClass.Account.class, org.onflow.protobuf.entities.AccountOuterClass.Account.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>bytes address = 1;</code>
     * @return The address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    public static final int BALANCE_FIELD_NUMBER = 2;
    private long balance_;
    /**
     * <code>uint64 balance = 2;</code>
     * @return The balance.
     */
    @java.lang.Override
    public long getBalance() {
      return balance_;
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString code_;
    /**
     * <code>bytes code = 3;</code>
     * @return The code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCode() {
      return code_;
    }

    public static final int KEYS_FIELD_NUMBER = 4;
    private java.util.List<org.onflow.protobuf.entities.AccountOuterClass.AccountKey> keys_;
    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    @java.lang.Override
    public java.util.List<org.onflow.protobuf.entities.AccountOuterClass.AccountKey> getKeysList() {
      return keys_;
    }
    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder> 
        getKeysOrBuilderList() {
      return keys_;
    }
    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    @java.lang.Override
    public int getKeysCount() {
      return keys_.size();
    }
    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    @java.lang.Override
    public org.onflow.protobuf.entities.AccountOuterClass.AccountKey getKeys(int index) {
      return keys_.get(index);
    }
    /**
     * <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    @java.lang.Override
    public org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder getKeysOrBuilder(
        int index) {
      return keys_.get(index);
    }

    public static final int CONTRACTS_FIELD_NUMBER = 5;
    private static final class ContractsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.ByteString> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                  org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_Account_ContractsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BYTES,
                  com.google.protobuf.ByteString.EMPTY);
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> contracts_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetContracts() {
      if (contracts_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ContractsDefaultEntryHolder.defaultEntry);
      }
      return contracts_;
    }

    public int getContractsCount() {
      return internalGetContracts().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; contracts = 5;</code>
     */

    @java.lang.Override
    public boolean containsContracts(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetContracts().getMap().containsKey(key);
    }
    /**
     * Use {@link #getContractsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getContracts() {
      return getContractsMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; contracts = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getContractsMap() {
      return internalGetContracts().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; contracts = 5;</code>
     */
    @java.lang.Override

    public com.google.protobuf.ByteString getContractsOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetContracts().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; contracts = 5;</code>
     */
    @java.lang.Override

    public com.google.protobuf.ByteString getContractsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetContracts().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!address_.isEmpty()) {
        output.writeBytes(1, address_);
      }
      if (balance_ != 0L) {
        output.writeUInt64(2, balance_);
      }
      if (!code_.isEmpty()) {
        output.writeBytes(3, code_);
      }
      for (int i = 0; i < keys_.size(); i++) {
        output.writeMessage(4, keys_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetContracts(),
          ContractsDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, address_);
      }
      if (balance_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, balance_);
      }
      if (!code_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, code_);
      }
      for (int i = 0; i < keys_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, keys_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
           : internalGetContracts().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
        contracts__ = ContractsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, contracts__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onflow.protobuf.entities.AccountOuterClass.Account)) {
        return super.equals(obj);
      }
      org.onflow.protobuf.entities.AccountOuterClass.Account other = (org.onflow.protobuf.entities.AccountOuterClass.Account) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (getBalance()
          != other.getBalance()) return false;
      if (!getCode()
          .equals(other.getCode())) return false;
      if (!getKeysList()
          .equals(other.getKeysList())) return false;
      if (!internalGetContracts().equals(
          other.internalGetContracts())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBalance());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      if (getKeysCount() > 0) {
        hash = (37 * hash) + KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getKeysList().hashCode();
      }
      if (!internalGetContracts().getMap().isEmpty()) {
        hash = (37 * hash) + CONTRACTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetContracts().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.Account parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onflow.protobuf.entities.AccountOuterClass.Account prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code flow.entities.Account}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:flow.entities.Account)
        org.onflow.protobuf.entities.AccountOuterClass.AccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_Account_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetContracts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableContracts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_Account_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onflow.protobuf.entities.AccountOuterClass.Account.class, org.onflow.protobuf.entities.AccountOuterClass.Account.Builder.class);
      }

      // Construct using org.onflow.protobuf.entities.AccountOuterClass.Account.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getKeysFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        address_ = com.google.protobuf.ByteString.EMPTY;

        balance_ = 0L;

        code_ = com.google.protobuf.ByteString.EMPTY;

        if (keysBuilder_ == null) {
          keys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          keysBuilder_.clear();
        }
        internalGetMutableContracts().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_Account_descriptor;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.AccountOuterClass.Account getDefaultInstanceForType() {
        return org.onflow.protobuf.entities.AccountOuterClass.Account.getDefaultInstance();
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.AccountOuterClass.Account build() {
        org.onflow.protobuf.entities.AccountOuterClass.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.AccountOuterClass.Account buildPartial() {
        org.onflow.protobuf.entities.AccountOuterClass.Account result = new org.onflow.protobuf.entities.AccountOuterClass.Account(this);
        int from_bitField0_ = bitField0_;
        result.address_ = address_;
        result.balance_ = balance_;
        result.code_ = code_;
        if (keysBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            keys_ = java.util.Collections.unmodifiableList(keys_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.keys_ = keys_;
        } else {
          result.keys_ = keysBuilder_.build();
        }
        result.contracts_ = internalGetContracts();
        result.contracts_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onflow.protobuf.entities.AccountOuterClass.Account) {
          return mergeFrom((org.onflow.protobuf.entities.AccountOuterClass.Account)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onflow.protobuf.entities.AccountOuterClass.Account other) {
        if (other == org.onflow.protobuf.entities.AccountOuterClass.Account.getDefaultInstance()) return this;
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        if (other.getBalance() != 0L) {
          setBalance(other.getBalance());
        }
        if (other.getCode() != com.google.protobuf.ByteString.EMPTY) {
          setCode(other.getCode());
        }
        if (keysBuilder_ == null) {
          if (!other.keys_.isEmpty()) {
            if (keys_.isEmpty()) {
              keys_ = other.keys_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureKeysIsMutable();
              keys_.addAll(other.keys_);
            }
            onChanged();
          }
        } else {
          if (!other.keys_.isEmpty()) {
            if (keysBuilder_.isEmpty()) {
              keysBuilder_.dispose();
              keysBuilder_ = null;
              keys_ = other.keys_;
              bitField0_ = (bitField0_ & ~0x00000001);
              keysBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKeysFieldBuilder() : null;
            } else {
              keysBuilder_.addAllMessages(other.keys_);
            }
          }
        }
        internalGetMutableContracts().mergeFrom(
            other.internalGetContracts());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onflow.protobuf.entities.AccountOuterClass.Account parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onflow.protobuf.entities.AccountOuterClass.Account) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes address = 1;</code>
       * @return The address.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>bytes address = 1;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      private long balance_ ;
      /**
       * <code>uint64 balance = 2;</code>
       * @return The balance.
       */
      @java.lang.Override
      public long getBalance() {
        return balance_;
      }
      /**
       * <code>uint64 balance = 2;</code>
       * @param value The balance to set.
       * @return This builder for chaining.
       */
      public Builder setBalance(long value) {
        
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 balance = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBalance() {
        
        balance_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString code_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes code = 3;</code>
       * @return The code.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCode() {
        return code_;
      }
      /**
       * <code>bytes code = 3;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }

      private java.util.List<org.onflow.protobuf.entities.AccountOuterClass.AccountKey> keys_ =
        java.util.Collections.emptyList();
      private void ensureKeysIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          keys_ = new java.util.ArrayList<org.onflow.protobuf.entities.AccountOuterClass.AccountKey>(keys_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.onflow.protobuf.entities.AccountOuterClass.AccountKey, org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder, org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder> keysBuilder_;

      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public java.util.List<org.onflow.protobuf.entities.AccountOuterClass.AccountKey> getKeysList() {
        if (keysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(keys_);
        } else {
          return keysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public int getKeysCount() {
        if (keysBuilder_ == null) {
          return keys_.size();
        } else {
          return keysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public org.onflow.protobuf.entities.AccountOuterClass.AccountKey getKeys(int index) {
        if (keysBuilder_ == null) {
          return keys_.get(index);
        } else {
          return keysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public Builder setKeys(
          int index, org.onflow.protobuf.entities.AccountOuterClass.AccountKey value) {
        if (keysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeysIsMutable();
          keys_.set(index, value);
          onChanged();
        } else {
          keysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public Builder setKeys(
          int index, org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder builderForValue) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          keys_.set(index, builderForValue.build());
          onChanged();
        } else {
          keysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public Builder addKeys(org.onflow.protobuf.entities.AccountOuterClass.AccountKey value) {
        if (keysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeysIsMutable();
          keys_.add(value);
          onChanged();
        } else {
          keysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public Builder addKeys(
          int index, org.onflow.protobuf.entities.AccountOuterClass.AccountKey value) {
        if (keysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeysIsMutable();
          keys_.add(index, value);
          onChanged();
        } else {
          keysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public Builder addKeys(
          org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder builderForValue) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          keys_.add(builderForValue.build());
          onChanged();
        } else {
          keysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public Builder addKeys(
          int index, org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder builderForValue) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          keys_.add(index, builderForValue.build());
          onChanged();
        } else {
          keysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public Builder addAllKeys(
          java.lang.Iterable<? extends org.onflow.protobuf.entities.AccountOuterClass.AccountKey> values) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, keys_);
          onChanged();
        } else {
          keysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public Builder clearKeys() {
        if (keysBuilder_ == null) {
          keys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          keysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public Builder removeKeys(int index) {
        if (keysBuilder_ == null) {
          ensureKeysIsMutable();
          keys_.remove(index);
          onChanged();
        } else {
          keysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder getKeysBuilder(
          int index) {
        return getKeysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder getKeysOrBuilder(
          int index) {
        if (keysBuilder_ == null) {
          return keys_.get(index);  } else {
          return keysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public java.util.List<? extends org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder> 
           getKeysOrBuilderList() {
        if (keysBuilder_ != null) {
          return keysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(keys_);
        }
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder addKeysBuilder() {
        return getKeysFieldBuilder().addBuilder(
            org.onflow.protobuf.entities.AccountOuterClass.AccountKey.getDefaultInstance());
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder addKeysBuilder(
          int index) {
        return getKeysFieldBuilder().addBuilder(
            index, org.onflow.protobuf.entities.AccountOuterClass.AccountKey.getDefaultInstance());
      }
      /**
       * <code>repeated .flow.entities.AccountKey keys = 4;</code>
       */
      public java.util.List<org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder> 
           getKeysBuilderList() {
        return getKeysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.onflow.protobuf.entities.AccountOuterClass.AccountKey, org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder, org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder> 
          getKeysFieldBuilder() {
        if (keysBuilder_ == null) {
          keysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.onflow.protobuf.entities.AccountOuterClass.AccountKey, org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder, org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder>(
                  keys_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          keys_ = null;
        }
        return keysBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.ByteString> contracts_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
      internalGetContracts() {
        if (contracts_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ContractsDefaultEntryHolder.defaultEntry);
        }
        return contracts_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
      internalGetMutableContracts() {
        onChanged();;
        if (contracts_ == null) {
          contracts_ = com.google.protobuf.MapField.newMapField(
              ContractsDefaultEntryHolder.defaultEntry);
        }
        if (!contracts_.isMutable()) {
          contracts_ = contracts_.copy();
        }
        return contracts_;
      }

      public int getContractsCount() {
        return internalGetContracts().getMap().size();
      }
      /**
       * <code>map&lt;string, bytes&gt; contracts = 5;</code>
       */

      @java.lang.Override
      public boolean containsContracts(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetContracts().getMap().containsKey(key);
      }
      /**
       * Use {@link #getContractsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getContracts() {
        return getContractsMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; contracts = 5;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getContractsMap() {
        return internalGetContracts().getMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; contracts = 5;</code>
       */
      @java.lang.Override

      public com.google.protobuf.ByteString getContractsOrDefault(
          java.lang.String key,
          com.google.protobuf.ByteString defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetContracts().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, bytes&gt; contracts = 5;</code>
       */
      @java.lang.Override

      public com.google.protobuf.ByteString getContractsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetContracts().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearContracts() {
        internalGetMutableContracts().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; contracts = 5;</code>
       */

      public Builder removeContracts(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableContracts().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
      getMutableContracts() {
        return internalGetMutableContracts().getMutableMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; contracts = 5;</code>
       */
      public Builder putContracts(
          java.lang.String key,
          com.google.protobuf.ByteString value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableContracts().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; contracts = 5;</code>
       */

      public Builder putAllContracts(
          java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
        internalGetMutableContracts().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:flow.entities.Account)
    }

    // @@protoc_insertion_point(class_scope:flow.entities.Account)
    private static final org.onflow.protobuf.entities.AccountOuterClass.Account DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onflow.protobuf.entities.AccountOuterClass.Account();
    }

    public static org.onflow.protobuf.entities.AccountOuterClass.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Account>
        PARSER = new com.google.protobuf.AbstractParser<Account>() {
      @java.lang.Override
      public Account parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Account(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Account> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onflow.protobuf.entities.AccountOuterClass.Account getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AccountKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:flow.entities.AccountKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <code>bytes public_key = 2;</code>
     * @return The publicKey.
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <code>uint32 sign_algo = 3;</code>
     * @return The signAlgo.
     */
    int getSignAlgo();

    /**
     * <code>uint32 hash_algo = 4;</code>
     * @return The hashAlgo.
     */
    int getHashAlgo();

    /**
     * <code>uint32 weight = 5;</code>
     * @return The weight.
     */
    int getWeight();

    /**
     * <code>uint32 sequence_number = 6;</code>
     * @return The sequenceNumber.
     */
    int getSequenceNumber();

    /**
     * <code>bool revoked = 7;</code>
     * @return The revoked.
     */
    boolean getRevoked();
  }
  /**
   * Protobuf type {@code flow.entities.AccountKey}
   */
  public static final class AccountKey extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:flow.entities.AccountKey)
      AccountKeyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccountKey.newBuilder() to construct.
    private AccountKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountKey() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AccountKey();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AccountKey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              index_ = input.readUInt32();
              break;
            }
            case 18: {

              publicKey_ = input.readBytes();
              break;
            }
            case 24: {

              signAlgo_ = input.readUInt32();
              break;
            }
            case 32: {

              hashAlgo_ = input.readUInt32();
              break;
            }
            case 40: {

              weight_ = input.readUInt32();
              break;
            }
            case 48: {

              sequenceNumber_ = input.readUInt32();
              break;
            }
            case 56: {

              revoked_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_AccountKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_AccountKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onflow.protobuf.entities.AccountOuterClass.AccountKey.class, org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }

    public static final int PUBLIC_KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>bytes public_key = 2;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int SIGN_ALGO_FIELD_NUMBER = 3;
    private int signAlgo_;
    /**
     * <code>uint32 sign_algo = 3;</code>
     * @return The signAlgo.
     */
    @java.lang.Override
    public int getSignAlgo() {
      return signAlgo_;
    }

    public static final int HASH_ALGO_FIELD_NUMBER = 4;
    private int hashAlgo_;
    /**
     * <code>uint32 hash_algo = 4;</code>
     * @return The hashAlgo.
     */
    @java.lang.Override
    public int getHashAlgo() {
      return hashAlgo_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 5;
    private int weight_;
    /**
     * <code>uint32 weight = 5;</code>
     * @return The weight.
     */
    @java.lang.Override
    public int getWeight() {
      return weight_;
    }

    public static final int SEQUENCE_NUMBER_FIELD_NUMBER = 6;
    private int sequenceNumber_;
    /**
     * <code>uint32 sequence_number = 6;</code>
     * @return The sequenceNumber.
     */
    @java.lang.Override
    public int getSequenceNumber() {
      return sequenceNumber_;
    }

    public static final int REVOKED_FIELD_NUMBER = 7;
    private boolean revoked_;
    /**
     * <code>bool revoked = 7;</code>
     * @return The revoked.
     */
    @java.lang.Override
    public boolean getRevoked() {
      return revoked_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeUInt32(1, index_);
      }
      if (!publicKey_.isEmpty()) {
        output.writeBytes(2, publicKey_);
      }
      if (signAlgo_ != 0) {
        output.writeUInt32(3, signAlgo_);
      }
      if (hashAlgo_ != 0) {
        output.writeUInt32(4, hashAlgo_);
      }
      if (weight_ != 0) {
        output.writeUInt32(5, weight_);
      }
      if (sequenceNumber_ != 0) {
        output.writeUInt32(6, sequenceNumber_);
      }
      if (revoked_ != false) {
        output.writeBool(7, revoked_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, index_);
      }
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, publicKey_);
      }
      if (signAlgo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, signAlgo_);
      }
      if (hashAlgo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, hashAlgo_);
      }
      if (weight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, weight_);
      }
      if (sequenceNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, sequenceNumber_);
      }
      if (revoked_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, revoked_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onflow.protobuf.entities.AccountOuterClass.AccountKey)) {
        return super.equals(obj);
      }
      org.onflow.protobuf.entities.AccountOuterClass.AccountKey other = (org.onflow.protobuf.entities.AccountOuterClass.AccountKey) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (!getPublicKey()
          .equals(other.getPublicKey())) return false;
      if (getSignAlgo()
          != other.getSignAlgo()) return false;
      if (getHashAlgo()
          != other.getHashAlgo()) return false;
      if (getWeight()
          != other.getWeight()) return false;
      if (getSequenceNumber()
          != other.getSequenceNumber()) return false;
      if (getRevoked()
          != other.getRevoked()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + SIGN_ALGO_FIELD_NUMBER;
      hash = (53 * hash) + getSignAlgo();
      hash = (37 * hash) + HASH_ALGO_FIELD_NUMBER;
      hash = (53 * hash) + getHashAlgo();
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getWeight();
      hash = (37 * hash) + SEQUENCE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSequenceNumber();
      hash = (37 * hash) + REVOKED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRevoked());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onflow.protobuf.entities.AccountOuterClass.AccountKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code flow.entities.AccountKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:flow.entities.AccountKey)
        org.onflow.protobuf.entities.AccountOuterClass.AccountKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_AccountKey_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_AccountKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onflow.protobuf.entities.AccountOuterClass.AccountKey.class, org.onflow.protobuf.entities.AccountOuterClass.AccountKey.Builder.class);
      }

      // Construct using org.onflow.protobuf.entities.AccountOuterClass.AccountKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = 0;

        publicKey_ = com.google.protobuf.ByteString.EMPTY;

        signAlgo_ = 0;

        hashAlgo_ = 0;

        weight_ = 0;

        sequenceNumber_ = 0;

        revoked_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onflow.protobuf.entities.AccountOuterClass.internal_static_flow_entities_AccountKey_descriptor;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.AccountOuterClass.AccountKey getDefaultInstanceForType() {
        return org.onflow.protobuf.entities.AccountOuterClass.AccountKey.getDefaultInstance();
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.AccountOuterClass.AccountKey build() {
        org.onflow.protobuf.entities.AccountOuterClass.AccountKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.AccountOuterClass.AccountKey buildPartial() {
        org.onflow.protobuf.entities.AccountOuterClass.AccountKey result = new org.onflow.protobuf.entities.AccountOuterClass.AccountKey(this);
        result.index_ = index_;
        result.publicKey_ = publicKey_;
        result.signAlgo_ = signAlgo_;
        result.hashAlgo_ = hashAlgo_;
        result.weight_ = weight_;
        result.sequenceNumber_ = sequenceNumber_;
        result.revoked_ = revoked_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onflow.protobuf.entities.AccountOuterClass.AccountKey) {
          return mergeFrom((org.onflow.protobuf.entities.AccountOuterClass.AccountKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onflow.protobuf.entities.AccountOuterClass.AccountKey other) {
        if (other == org.onflow.protobuf.entities.AccountOuterClass.AccountKey.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setPublicKey(other.getPublicKey());
        }
        if (other.getSignAlgo() != 0) {
          setSignAlgo(other.getSignAlgo());
        }
        if (other.getHashAlgo() != 0) {
          setHashAlgo(other.getHashAlgo());
        }
        if (other.getWeight() != 0) {
          setWeight(other.getWeight());
        }
        if (other.getSequenceNumber() != 0) {
          setSequenceNumber(other.getSequenceNumber());
        }
        if (other.getRevoked() != false) {
          setRevoked(other.getRevoked());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onflow.protobuf.entities.AccountOuterClass.AccountKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onflow.protobuf.entities.AccountOuterClass.AccountKey) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int index_ ;
      /**
       * <code>uint32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return index_;
      }
      /**
       * <code>uint32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes public_key = 2;</code>
       * @return The publicKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes public_key = 2;</code>
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes public_key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private int signAlgo_ ;
      /**
       * <code>uint32 sign_algo = 3;</code>
       * @return The signAlgo.
       */
      @java.lang.Override
      public int getSignAlgo() {
        return signAlgo_;
      }
      /**
       * <code>uint32 sign_algo = 3;</code>
       * @param value The signAlgo to set.
       * @return This builder for chaining.
       */
      public Builder setSignAlgo(int value) {
        
        signAlgo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sign_algo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignAlgo() {
        
        signAlgo_ = 0;
        onChanged();
        return this;
      }

      private int hashAlgo_ ;
      /**
       * <code>uint32 hash_algo = 4;</code>
       * @return The hashAlgo.
       */
      @java.lang.Override
      public int getHashAlgo() {
        return hashAlgo_;
      }
      /**
       * <code>uint32 hash_algo = 4;</code>
       * @param value The hashAlgo to set.
       * @return This builder for chaining.
       */
      public Builder setHashAlgo(int value) {
        
        hashAlgo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 hash_algo = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHashAlgo() {
        
        hashAlgo_ = 0;
        onChanged();
        return this;
      }

      private int weight_ ;
      /**
       * <code>uint32 weight = 5;</code>
       * @return The weight.
       */
      @java.lang.Override
      public int getWeight() {
        return weight_;
      }
      /**
       * <code>uint32 weight = 5;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(int value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 weight = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        
        weight_ = 0;
        onChanged();
        return this;
      }

      private int sequenceNumber_ ;
      /**
       * <code>uint32 sequence_number = 6;</code>
       * @return The sequenceNumber.
       */
      @java.lang.Override
      public int getSequenceNumber() {
        return sequenceNumber_;
      }
      /**
       * <code>uint32 sequence_number = 6;</code>
       * @param value The sequenceNumber to set.
       * @return This builder for chaining.
       */
      public Builder setSequenceNumber(int value) {
        
        sequenceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sequence_number = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequenceNumber() {
        
        sequenceNumber_ = 0;
        onChanged();
        return this;
      }

      private boolean revoked_ ;
      /**
       * <code>bool revoked = 7;</code>
       * @return The revoked.
       */
      @java.lang.Override
      public boolean getRevoked() {
        return revoked_;
      }
      /**
       * <code>bool revoked = 7;</code>
       * @param value The revoked to set.
       * @return This builder for chaining.
       */
      public Builder setRevoked(boolean value) {
        
        revoked_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool revoked = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRevoked() {
        
        revoked_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:flow.entities.AccountKey)
    }

    // @@protoc_insertion_point(class_scope:flow.entities.AccountKey)
    private static final org.onflow.protobuf.entities.AccountOuterClass.AccountKey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onflow.protobuf.entities.AccountOuterClass.AccountKey();
    }

    public static org.onflow.protobuf.entities.AccountOuterClass.AccountKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountKey>
        PARSER = new com.google.protobuf.AbstractParser<AccountKey>() {
      @java.lang.Override
      public AccountKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountKey(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccountKey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountKey> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onflow.protobuf.entities.AccountOuterClass.AccountKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flow_entities_Account_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_flow_entities_Account_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flow_entities_Account_ContractsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_flow_entities_Account_ContractsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flow_entities_AccountKey_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_flow_entities_AccountKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033flow/entities/account.proto\022\rflow.enti" +
      "ties\"\316\001\n\007Account\022\017\n\007address\030\001 \001(\014\022\017\n\007bal" +
      "ance\030\002 \001(\004\022\014\n\004code\030\003 \001(\014\022\'\n\004keys\030\004 \003(\0132\031" +
      ".flow.entities.AccountKey\0228\n\tcontracts\030\005" +
      " \003(\0132%.flow.entities.Account.ContractsEn" +
      "try\0320\n\016ContractsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\014:\0028\001\"\217\001\n\nAccountKey\022\r\n\005index\030\001 " +
      "\001(\r\022\022\n\npublic_key\030\002 \001(\014\022\021\n\tsign_algo\030\003 \001" +
      "(\r\022\021\n\thash_algo\030\004 \001(\r\022\016\n\006weight\030\005 \001(\r\022\027\n" +
      "\017sequence_number\030\006 \001(\r\022\017\n\007revoked\030\007 \001(\010B" +
      "P\n\034org.onflow.protobuf.entitiesZ0github." +
      "com/onflow/flow/protobuf/go/flow/entitie" +
      "sb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_flow_entities_Account_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_flow_entities_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_flow_entities_Account_descriptor,
        new java.lang.String[] { "Address", "Balance", "Code", "Keys", "Contracts", });
    internal_static_flow_entities_Account_ContractsEntry_descriptor =
      internal_static_flow_entities_Account_descriptor.getNestedTypes().get(0);
    internal_static_flow_entities_Account_ContractsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_flow_entities_Account_ContractsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_flow_entities_AccountKey_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_flow_entities_AccountKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_flow_entities_AccountKey_descriptor,
        new java.lang.String[] { "Index", "PublicKey", "SignAlgo", "HashAlgo", "Weight", "SequenceNumber", "Revoked", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
