// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flow/entities/block_seal.proto

package org.onflow.protobuf.entities;

public final class BlockSealOuterClass {
  private BlockSealOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockSealOrBuilder extends
      // @@protoc_insertion_point(interface_extends:flow.entities.BlockSeal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes block_id = 1;</code>
     * @return The blockId.
     */
    com.google.protobuf.ByteString getBlockId();

    /**
     * <code>bytes execution_receipt_id = 2;</code>
     * @return The executionReceiptId.
     */
    com.google.protobuf.ByteString getExecutionReceiptId();

    /**
     * <code>repeated bytes execution_receipt_signatures = 3;</code>
     * @return A list containing the executionReceiptSignatures.
     */
    java.util.List<com.google.protobuf.ByteString> getExecutionReceiptSignaturesList();
    /**
     * <code>repeated bytes execution_receipt_signatures = 3;</code>
     * @return The count of executionReceiptSignatures.
     */
    int getExecutionReceiptSignaturesCount();
    /**
     * <code>repeated bytes execution_receipt_signatures = 3;</code>
     * @param index The index of the element to return.
     * @return The executionReceiptSignatures at the given index.
     */
    com.google.protobuf.ByteString getExecutionReceiptSignatures(int index);

    /**
     * <code>repeated bytes result_approval_signatures = 4;</code>
     * @return A list containing the resultApprovalSignatures.
     */
    java.util.List<com.google.protobuf.ByteString> getResultApprovalSignaturesList();
    /**
     * <code>repeated bytes result_approval_signatures = 4;</code>
     * @return The count of resultApprovalSignatures.
     */
    int getResultApprovalSignaturesCount();
    /**
     * <code>repeated bytes result_approval_signatures = 4;</code>
     * @param index The index of the element to return.
     * @return The resultApprovalSignatures at the given index.
     */
    com.google.protobuf.ByteString getResultApprovalSignatures(int index);
  }
  /**
   * Protobuf type {@code flow.entities.BlockSeal}
   */
  public static final class BlockSeal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:flow.entities.BlockSeal)
      BlockSealOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlockSeal.newBuilder() to construct.
    private BlockSeal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockSeal() {
      blockId_ = com.google.protobuf.ByteString.EMPTY;
      executionReceiptId_ = com.google.protobuf.ByteString.EMPTY;
      executionReceiptSignatures_ = java.util.Collections.emptyList();
      resultApprovalSignatures_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BlockSeal();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockSeal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              blockId_ = input.readBytes();
              break;
            }
            case 18: {

              executionReceiptId_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                executionReceiptSignatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              executionReceiptSignatures_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                resultApprovalSignatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              resultApprovalSignatures_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          executionReceiptSignatures_ = java.util.Collections.unmodifiableList(executionReceiptSignatures_); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          resultApprovalSignatures_ = java.util.Collections.unmodifiableList(resultApprovalSignatures_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onflow.protobuf.entities.BlockSealOuterClass.internal_static_flow_entities_BlockSeal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onflow.protobuf.entities.BlockSealOuterClass.internal_static_flow_entities_BlockSeal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal.class, org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal.Builder.class);
    }

    public static final int BLOCK_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString blockId_;
    /**
     * <code>bytes block_id = 1;</code>
     * @return The blockId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBlockId() {
      return blockId_;
    }

    public static final int EXECUTION_RECEIPT_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString executionReceiptId_;
    /**
     * <code>bytes execution_receipt_id = 2;</code>
     * @return The executionReceiptId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getExecutionReceiptId() {
      return executionReceiptId_;
    }

    public static final int EXECUTION_RECEIPT_SIGNATURES_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> executionReceiptSignatures_;
    /**
     * <code>repeated bytes execution_receipt_signatures = 3;</code>
     * @return A list containing the executionReceiptSignatures.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getExecutionReceiptSignaturesList() {
      return executionReceiptSignatures_;
    }
    /**
     * <code>repeated bytes execution_receipt_signatures = 3;</code>
     * @return The count of executionReceiptSignatures.
     */
    public int getExecutionReceiptSignaturesCount() {
      return executionReceiptSignatures_.size();
    }
    /**
     * <code>repeated bytes execution_receipt_signatures = 3;</code>
     * @param index The index of the element to return.
     * @return The executionReceiptSignatures at the given index.
     */
    public com.google.protobuf.ByteString getExecutionReceiptSignatures(int index) {
      return executionReceiptSignatures_.get(index);
    }

    public static final int RESULT_APPROVAL_SIGNATURES_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> resultApprovalSignatures_;
    /**
     * <code>repeated bytes result_approval_signatures = 4;</code>
     * @return A list containing the resultApprovalSignatures.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getResultApprovalSignaturesList() {
      return resultApprovalSignatures_;
    }
    /**
     * <code>repeated bytes result_approval_signatures = 4;</code>
     * @return The count of resultApprovalSignatures.
     */
    public int getResultApprovalSignaturesCount() {
      return resultApprovalSignatures_.size();
    }
    /**
     * <code>repeated bytes result_approval_signatures = 4;</code>
     * @param index The index of the element to return.
     * @return The resultApprovalSignatures at the given index.
     */
    public com.google.protobuf.ByteString getResultApprovalSignatures(int index) {
      return resultApprovalSignatures_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!blockId_.isEmpty()) {
        output.writeBytes(1, blockId_);
      }
      if (!executionReceiptId_.isEmpty()) {
        output.writeBytes(2, executionReceiptId_);
      }
      for (int i = 0; i < executionReceiptSignatures_.size(); i++) {
        output.writeBytes(3, executionReceiptSignatures_.get(i));
      }
      for (int i = 0; i < resultApprovalSignatures_.size(); i++) {
        output.writeBytes(4, resultApprovalSignatures_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!blockId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, blockId_);
      }
      if (!executionReceiptId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, executionReceiptId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < executionReceiptSignatures_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(executionReceiptSignatures_.get(i));
        }
        size += dataSize;
        size += 1 * getExecutionReceiptSignaturesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < resultApprovalSignatures_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(resultApprovalSignatures_.get(i));
        }
        size += dataSize;
        size += 1 * getResultApprovalSignaturesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal)) {
        return super.equals(obj);
      }
      org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal other = (org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal) obj;

      if (!getBlockId()
          .equals(other.getBlockId())) return false;
      if (!getExecutionReceiptId()
          .equals(other.getExecutionReceiptId())) return false;
      if (!getExecutionReceiptSignaturesList()
          .equals(other.getExecutionReceiptSignaturesList())) return false;
      if (!getResultApprovalSignaturesList()
          .equals(other.getResultApprovalSignaturesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBlockId().hashCode();
      hash = (37 * hash) + EXECUTION_RECEIPT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getExecutionReceiptId().hashCode();
      if (getExecutionReceiptSignaturesCount() > 0) {
        hash = (37 * hash) + EXECUTION_RECEIPT_SIGNATURES_FIELD_NUMBER;
        hash = (53 * hash) + getExecutionReceiptSignaturesList().hashCode();
      }
      if (getResultApprovalSignaturesCount() > 0) {
        hash = (37 * hash) + RESULT_APPROVAL_SIGNATURES_FIELD_NUMBER;
        hash = (53 * hash) + getResultApprovalSignaturesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code flow.entities.BlockSeal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:flow.entities.BlockSeal)
        org.onflow.protobuf.entities.BlockSealOuterClass.BlockSealOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onflow.protobuf.entities.BlockSealOuterClass.internal_static_flow_entities_BlockSeal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onflow.protobuf.entities.BlockSealOuterClass.internal_static_flow_entities_BlockSeal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal.class, org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal.Builder.class);
      }

      // Construct using org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blockId_ = com.google.protobuf.ByteString.EMPTY;

        executionReceiptId_ = com.google.protobuf.ByteString.EMPTY;

        executionReceiptSignatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        resultApprovalSignatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onflow.protobuf.entities.BlockSealOuterClass.internal_static_flow_entities_BlockSeal_descriptor;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal getDefaultInstanceForType() {
        return org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal.getDefaultInstance();
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal build() {
        org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal buildPartial() {
        org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal result = new org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal(this);
        int from_bitField0_ = bitField0_;
        result.blockId_ = blockId_;
        result.executionReceiptId_ = executionReceiptId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          executionReceiptSignatures_ = java.util.Collections.unmodifiableList(executionReceiptSignatures_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.executionReceiptSignatures_ = executionReceiptSignatures_;
        if (((bitField0_ & 0x00000002) != 0)) {
          resultApprovalSignatures_ = java.util.Collections.unmodifiableList(resultApprovalSignatures_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.resultApprovalSignatures_ = resultApprovalSignatures_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal) {
          return mergeFrom((org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal other) {
        if (other == org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal.getDefaultInstance()) return this;
        if (other.getBlockId() != com.google.protobuf.ByteString.EMPTY) {
          setBlockId(other.getBlockId());
        }
        if (other.getExecutionReceiptId() != com.google.protobuf.ByteString.EMPTY) {
          setExecutionReceiptId(other.getExecutionReceiptId());
        }
        if (!other.executionReceiptSignatures_.isEmpty()) {
          if (executionReceiptSignatures_.isEmpty()) {
            executionReceiptSignatures_ = other.executionReceiptSignatures_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureExecutionReceiptSignaturesIsMutable();
            executionReceiptSignatures_.addAll(other.executionReceiptSignatures_);
          }
          onChanged();
        }
        if (!other.resultApprovalSignatures_.isEmpty()) {
          if (resultApprovalSignatures_.isEmpty()) {
            resultApprovalSignatures_ = other.resultApprovalSignatures_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureResultApprovalSignaturesIsMutable();
            resultApprovalSignatures_.addAll(other.resultApprovalSignatures_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString blockId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes block_id = 1;</code>
       * @return The blockId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBlockId() {
        return blockId_;
      }
      /**
       * <code>bytes block_id = 1;</code>
       * @param value The blockId to set.
       * @return This builder for chaining.
       */
      public Builder setBlockId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        blockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes block_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockId() {
        
        blockId_ = getDefaultInstance().getBlockId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString executionReceiptId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes execution_receipt_id = 2;</code>
       * @return The executionReceiptId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getExecutionReceiptId() {
        return executionReceiptId_;
      }
      /**
       * <code>bytes execution_receipt_id = 2;</code>
       * @param value The executionReceiptId to set.
       * @return This builder for chaining.
       */
      public Builder setExecutionReceiptId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        executionReceiptId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes execution_receipt_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecutionReceiptId() {
        
        executionReceiptId_ = getDefaultInstance().getExecutionReceiptId();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> executionReceiptSignatures_ = java.util.Collections.emptyList();
      private void ensureExecutionReceiptSignaturesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          executionReceiptSignatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>(executionReceiptSignatures_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes execution_receipt_signatures = 3;</code>
       * @return A list containing the executionReceiptSignatures.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getExecutionReceiptSignaturesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(executionReceiptSignatures_) : executionReceiptSignatures_;
      }
      /**
       * <code>repeated bytes execution_receipt_signatures = 3;</code>
       * @return The count of executionReceiptSignatures.
       */
      public int getExecutionReceiptSignaturesCount() {
        return executionReceiptSignatures_.size();
      }
      /**
       * <code>repeated bytes execution_receipt_signatures = 3;</code>
       * @param index The index of the element to return.
       * @return The executionReceiptSignatures at the given index.
       */
      public com.google.protobuf.ByteString getExecutionReceiptSignatures(int index) {
        return executionReceiptSignatures_.get(index);
      }
      /**
       * <code>repeated bytes execution_receipt_signatures = 3;</code>
       * @param index The index to set the value at.
       * @param value The executionReceiptSignatures to set.
       * @return This builder for chaining.
       */
      public Builder setExecutionReceiptSignatures(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExecutionReceiptSignaturesIsMutable();
        executionReceiptSignatures_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes execution_receipt_signatures = 3;</code>
       * @param value The executionReceiptSignatures to add.
       * @return This builder for chaining.
       */
      public Builder addExecutionReceiptSignatures(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExecutionReceiptSignaturesIsMutable();
        executionReceiptSignatures_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes execution_receipt_signatures = 3;</code>
       * @param values The executionReceiptSignatures to add.
       * @return This builder for chaining.
       */
      public Builder addAllExecutionReceiptSignatures(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureExecutionReceiptSignaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, executionReceiptSignatures_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes execution_receipt_signatures = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecutionReceiptSignatures() {
        executionReceiptSignatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> resultApprovalSignatures_ = java.util.Collections.emptyList();
      private void ensureResultApprovalSignaturesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          resultApprovalSignatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>(resultApprovalSignatures_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes result_approval_signatures = 4;</code>
       * @return A list containing the resultApprovalSignatures.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getResultApprovalSignaturesList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(resultApprovalSignatures_) : resultApprovalSignatures_;
      }
      /**
       * <code>repeated bytes result_approval_signatures = 4;</code>
       * @return The count of resultApprovalSignatures.
       */
      public int getResultApprovalSignaturesCount() {
        return resultApprovalSignatures_.size();
      }
      /**
       * <code>repeated bytes result_approval_signatures = 4;</code>
       * @param index The index of the element to return.
       * @return The resultApprovalSignatures at the given index.
       */
      public com.google.protobuf.ByteString getResultApprovalSignatures(int index) {
        return resultApprovalSignatures_.get(index);
      }
      /**
       * <code>repeated bytes result_approval_signatures = 4;</code>
       * @param index The index to set the value at.
       * @param value The resultApprovalSignatures to set.
       * @return This builder for chaining.
       */
      public Builder setResultApprovalSignatures(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResultApprovalSignaturesIsMutable();
        resultApprovalSignatures_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes result_approval_signatures = 4;</code>
       * @param value The resultApprovalSignatures to add.
       * @return This builder for chaining.
       */
      public Builder addResultApprovalSignatures(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResultApprovalSignaturesIsMutable();
        resultApprovalSignatures_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes result_approval_signatures = 4;</code>
       * @param values The resultApprovalSignatures to add.
       * @return This builder for chaining.
       */
      public Builder addAllResultApprovalSignatures(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureResultApprovalSignaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, resultApprovalSignatures_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes result_approval_signatures = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearResultApprovalSignatures() {
        resultApprovalSignatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:flow.entities.BlockSeal)
    }

    // @@protoc_insertion_point(class_scope:flow.entities.BlockSeal)
    private static final org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal();
    }

    public static org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockSeal>
        PARSER = new com.google.protobuf.AbstractParser<BlockSeal>() {
      @java.lang.Override
      public BlockSeal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlockSeal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockSeal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockSeal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onflow.protobuf.entities.BlockSealOuterClass.BlockSeal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flow_entities_BlockSeal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_flow_entities_BlockSeal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036flow/entities/block_seal.proto\022\rflow.e" +
      "ntities\"\205\001\n\tBlockSeal\022\020\n\010block_id\030\001 \001(\014\022" +
      "\034\n\024execution_receipt_id\030\002 \001(\014\022$\n\034executi" +
      "on_receipt_signatures\030\003 \003(\014\022\"\n\032result_ap" +
      "proval_signatures\030\004 \003(\014BP\n\034org.onflow.pr" +
      "otobuf.entitiesZ0github.com/onflow/flow/" +
      "protobuf/go/flow/entitiesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_flow_entities_BlockSeal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_flow_entities_BlockSeal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_flow_entities_BlockSeal_descriptor,
        new java.lang.String[] { "BlockId", "ExecutionReceiptId", "ExecutionReceiptSignatures", "ResultApprovalSignatures", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
