// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flow/entities/collection.proto

package org.onflow.protobuf.entities;

public final class CollectionOuterClass {
  private CollectionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CollectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:flow.entities.Collection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes id = 1;</code>
     * @return The id.
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>repeated bytes transaction_ids = 2;</code>
     * @return A list containing the transactionIds.
     */
    java.util.List<com.google.protobuf.ByteString> getTransactionIdsList();
    /**
     * <code>repeated bytes transaction_ids = 2;</code>
     * @return The count of transactionIds.
     */
    int getTransactionIdsCount();
    /**
     * <code>repeated bytes transaction_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The transactionIds at the given index.
     */
    com.google.protobuf.ByteString getTransactionIds(int index);
  }
  /**
   * Protobuf type {@code flow.entities.Collection}
   */
  public static final class Collection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:flow.entities.Collection)
      CollectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Collection.newBuilder() to construct.
    private Collection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Collection() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      transactionIds_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Collection();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Collection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              id_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                transactionIds_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              transactionIds_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          transactionIds_ = java.util.Collections.unmodifiableList(transactionIds_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_Collection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_Collection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onflow.protobuf.entities.CollectionOuterClass.Collection.class, org.onflow.protobuf.entities.CollectionOuterClass.Collection.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>bytes id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int TRANSACTION_IDS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> transactionIds_;
    /**
     * <code>repeated bytes transaction_ids = 2;</code>
     * @return A list containing the transactionIds.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getTransactionIdsList() {
      return transactionIds_;
    }
    /**
     * <code>repeated bytes transaction_ids = 2;</code>
     * @return The count of transactionIds.
     */
    public int getTransactionIdsCount() {
      return transactionIds_.size();
    }
    /**
     * <code>repeated bytes transaction_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The transactionIds at the given index.
     */
    public com.google.protobuf.ByteString getTransactionIds(int index) {
      return transactionIds_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!id_.isEmpty()) {
        output.writeBytes(1, id_);
      }
      for (int i = 0; i < transactionIds_.size(); i++) {
        output.writeBytes(2, transactionIds_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!id_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < transactionIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(transactionIds_.get(i));
        }
        size += dataSize;
        size += 1 * getTransactionIdsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onflow.protobuf.entities.CollectionOuterClass.Collection)) {
        return super.equals(obj);
      }
      org.onflow.protobuf.entities.CollectionOuterClass.Collection other = (org.onflow.protobuf.entities.CollectionOuterClass.Collection) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getTransactionIdsList()
          .equals(other.getTransactionIdsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (getTransactionIdsCount() > 0) {
        hash = (37 * hash) + TRANSACTION_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onflow.protobuf.entities.CollectionOuterClass.Collection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code flow.entities.Collection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:flow.entities.Collection)
        org.onflow.protobuf.entities.CollectionOuterClass.CollectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_Collection_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_Collection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onflow.protobuf.entities.CollectionOuterClass.Collection.class, org.onflow.protobuf.entities.CollectionOuterClass.Collection.Builder.class);
      }

      // Construct using org.onflow.protobuf.entities.CollectionOuterClass.Collection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;

        transactionIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_Collection_descriptor;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.CollectionOuterClass.Collection getDefaultInstanceForType() {
        return org.onflow.protobuf.entities.CollectionOuterClass.Collection.getDefaultInstance();
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.CollectionOuterClass.Collection build() {
        org.onflow.protobuf.entities.CollectionOuterClass.Collection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.CollectionOuterClass.Collection buildPartial() {
        org.onflow.protobuf.entities.CollectionOuterClass.Collection result = new org.onflow.protobuf.entities.CollectionOuterClass.Collection(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        if (((bitField0_ & 0x00000001) != 0)) {
          transactionIds_ = java.util.Collections.unmodifiableList(transactionIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transactionIds_ = transactionIds_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onflow.protobuf.entities.CollectionOuterClass.Collection) {
          return mergeFrom((org.onflow.protobuf.entities.CollectionOuterClass.Collection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onflow.protobuf.entities.CollectionOuterClass.Collection other) {
        if (other == org.onflow.protobuf.entities.CollectionOuterClass.Collection.getDefaultInstance()) return this;
        if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
          setId(other.getId());
        }
        if (!other.transactionIds_.isEmpty()) {
          if (transactionIds_.isEmpty()) {
            transactionIds_ = other.transactionIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransactionIdsIsMutable();
            transactionIds_.addAll(other.transactionIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onflow.protobuf.entities.CollectionOuterClass.Collection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onflow.protobuf.entities.CollectionOuterClass.Collection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>bytes id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> transactionIds_ = java.util.Collections.emptyList();
      private void ensureTransactionIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          transactionIds_ = new java.util.ArrayList<com.google.protobuf.ByteString>(transactionIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes transaction_ids = 2;</code>
       * @return A list containing the transactionIds.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getTransactionIdsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(transactionIds_) : transactionIds_;
      }
      /**
       * <code>repeated bytes transaction_ids = 2;</code>
       * @return The count of transactionIds.
       */
      public int getTransactionIdsCount() {
        return transactionIds_.size();
      }
      /**
       * <code>repeated bytes transaction_ids = 2;</code>
       * @param index The index of the element to return.
       * @return The transactionIds at the given index.
       */
      public com.google.protobuf.ByteString getTransactionIds(int index) {
        return transactionIds_.get(index);
      }
      /**
       * <code>repeated bytes transaction_ids = 2;</code>
       * @param index The index to set the value at.
       * @param value The transactionIds to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionIds(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionIdsIsMutable();
        transactionIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transaction_ids = 2;</code>
       * @param value The transactionIds to add.
       * @return This builder for chaining.
       */
      public Builder addTransactionIds(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionIdsIsMutable();
        transactionIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transaction_ids = 2;</code>
       * @param values The transactionIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllTransactionIds(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureTransactionIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactionIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transaction_ids = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionIds() {
        transactionIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:flow.entities.Collection)
    }

    // @@protoc_insertion_point(class_scope:flow.entities.Collection)
    private static final org.onflow.protobuf.entities.CollectionOuterClass.Collection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onflow.protobuf.entities.CollectionOuterClass.Collection();
    }

    public static org.onflow.protobuf.entities.CollectionOuterClass.Collection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Collection>
        PARSER = new com.google.protobuf.AbstractParser<Collection>() {
      @java.lang.Override
      public Collection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Collection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Collection> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Collection> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onflow.protobuf.entities.CollectionOuterClass.Collection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CollectionGuaranteeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:flow.entities.CollectionGuarantee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes collection_id = 1;</code>
     * @return The collectionId.
     */
    com.google.protobuf.ByteString getCollectionId();

    /**
     * <code>repeated bytes signatures = 2;</code>
     * @return A list containing the signatures.
     */
    java.util.List<com.google.protobuf.ByteString> getSignaturesList();
    /**
     * <code>repeated bytes signatures = 2;</code>
     * @return The count of signatures.
     */
    int getSignaturesCount();
    /**
     * <code>repeated bytes signatures = 2;</code>
     * @param index The index of the element to return.
     * @return The signatures at the given index.
     */
    com.google.protobuf.ByteString getSignatures(int index);
  }
  /**
   * Protobuf type {@code flow.entities.CollectionGuarantee}
   */
  public static final class CollectionGuarantee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:flow.entities.CollectionGuarantee)
      CollectionGuaranteeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CollectionGuarantee.newBuilder() to construct.
    private CollectionGuarantee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CollectionGuarantee() {
      collectionId_ = com.google.protobuf.ByteString.EMPTY;
      signatures_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CollectionGuarantee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CollectionGuarantee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              collectionId_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                signatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              signatures_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          signatures_ = java.util.Collections.unmodifiableList(signatures_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_CollectionGuarantee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_CollectionGuarantee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee.class, org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee.Builder.class);
    }

    public static final int COLLECTION_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString collectionId_;
    /**
     * <code>bytes collection_id = 1;</code>
     * @return The collectionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCollectionId() {
      return collectionId_;
    }

    public static final int SIGNATURES_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> signatures_;
    /**
     * <code>repeated bytes signatures = 2;</code>
     * @return A list containing the signatures.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getSignaturesList() {
      return signatures_;
    }
    /**
     * <code>repeated bytes signatures = 2;</code>
     * @return The count of signatures.
     */
    public int getSignaturesCount() {
      return signatures_.size();
    }
    /**
     * <code>repeated bytes signatures = 2;</code>
     * @param index The index of the element to return.
     * @return The signatures at the given index.
     */
    public com.google.protobuf.ByteString getSignatures(int index) {
      return signatures_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!collectionId_.isEmpty()) {
        output.writeBytes(1, collectionId_);
      }
      for (int i = 0; i < signatures_.size(); i++) {
        output.writeBytes(2, signatures_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!collectionId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, collectionId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < signatures_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(signatures_.get(i));
        }
        size += dataSize;
        size += 1 * getSignaturesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee)) {
        return super.equals(obj);
      }
      org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee other = (org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee) obj;

      if (!getCollectionId()
          .equals(other.getCollectionId())) return false;
      if (!getSignaturesList()
          .equals(other.getSignaturesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COLLECTION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCollectionId().hashCode();
      if (getSignaturesCount() > 0) {
        hash = (37 * hash) + SIGNATURES_FIELD_NUMBER;
        hash = (53 * hash) + getSignaturesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code flow.entities.CollectionGuarantee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:flow.entities.CollectionGuarantee)
        org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuaranteeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_CollectionGuarantee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_CollectionGuarantee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee.class, org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee.Builder.class);
      }

      // Construct using org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        collectionId_ = com.google.protobuf.ByteString.EMPTY;

        signatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.onflow.protobuf.entities.CollectionOuterClass.internal_static_flow_entities_CollectionGuarantee_descriptor;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee getDefaultInstanceForType() {
        return org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee.getDefaultInstance();
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee build() {
        org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee buildPartial() {
        org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee result = new org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee(this);
        int from_bitField0_ = bitField0_;
        result.collectionId_ = collectionId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          signatures_ = java.util.Collections.unmodifiableList(signatures_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.signatures_ = signatures_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee) {
          return mergeFrom((org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee other) {
        if (other == org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee.getDefaultInstance()) return this;
        if (other.getCollectionId() != com.google.protobuf.ByteString.EMPTY) {
          setCollectionId(other.getCollectionId());
        }
        if (!other.signatures_.isEmpty()) {
          if (signatures_.isEmpty()) {
            signatures_ = other.signatures_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSignaturesIsMutable();
            signatures_.addAll(other.signatures_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString collectionId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes collection_id = 1;</code>
       * @return The collectionId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCollectionId() {
        return collectionId_;
      }
      /**
       * <code>bytes collection_id = 1;</code>
       * @param value The collectionId to set.
       * @return This builder for chaining.
       */
      public Builder setCollectionId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        collectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes collection_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCollectionId() {
        
        collectionId_ = getDefaultInstance().getCollectionId();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> signatures_ = java.util.Collections.emptyList();
      private void ensureSignaturesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          signatures_ = new java.util.ArrayList<com.google.protobuf.ByteString>(signatures_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes signatures = 2;</code>
       * @return A list containing the signatures.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getSignaturesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(signatures_) : signatures_;
      }
      /**
       * <code>repeated bytes signatures = 2;</code>
       * @return The count of signatures.
       */
      public int getSignaturesCount() {
        return signatures_.size();
      }
      /**
       * <code>repeated bytes signatures = 2;</code>
       * @param index The index of the element to return.
       * @return The signatures at the given index.
       */
      public com.google.protobuf.ByteString getSignatures(int index) {
        return signatures_.get(index);
      }
      /**
       * <code>repeated bytes signatures = 2;</code>
       * @param index The index to set the value at.
       * @param value The signatures to set.
       * @return This builder for chaining.
       */
      public Builder setSignatures(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignaturesIsMutable();
        signatures_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes signatures = 2;</code>
       * @param value The signatures to add.
       * @return This builder for chaining.
       */
      public Builder addSignatures(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSignaturesIsMutable();
        signatures_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes signatures = 2;</code>
       * @param values The signatures to add.
       * @return This builder for chaining.
       */
      public Builder addAllSignatures(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureSignaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, signatures_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes signatures = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignatures() {
        signatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:flow.entities.CollectionGuarantee)
    }

    // @@protoc_insertion_point(class_scope:flow.entities.CollectionGuarantee)
    private static final org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee();
    }

    public static org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CollectionGuarantee>
        PARSER = new com.google.protobuf.AbstractParser<CollectionGuarantee>() {
      @java.lang.Override
      public CollectionGuarantee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CollectionGuarantee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CollectionGuarantee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CollectionGuarantee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.onflow.protobuf.entities.CollectionOuterClass.CollectionGuarantee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flow_entities_Collection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_flow_entities_Collection_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flow_entities_CollectionGuarantee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_flow_entities_CollectionGuarantee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036flow/entities/collection.proto\022\rflow.e" +
      "ntities\"1\n\nCollection\022\n\n\002id\030\001 \001(\014\022\027\n\017tra" +
      "nsaction_ids\030\002 \003(\014\"@\n\023CollectionGuarante" +
      "e\022\025\n\rcollection_id\030\001 \001(\014\022\022\n\nsignatures\030\002" +
      " \003(\014BP\n\034org.onflow.protobuf.entitiesZ0gi" +
      "thub.com/onflow/flow/protobuf/go/flow/en" +
      "titiesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_flow_entities_Collection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_flow_entities_Collection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_flow_entities_Collection_descriptor,
        new java.lang.String[] { "Id", "TransactionIds", });
    internal_static_flow_entities_CollectionGuarantee_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_flow_entities_CollectionGuarantee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_flow_entities_CollectionGuarantee_descriptor,
        new java.lang.String[] { "CollectionId", "Signatures", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
